### ISSUE TITLE
Correctness of detected data

### ISSUE THREAD

**Issue by anbilly19** [harishk30/RingGalaxiesCNNAnalysis#1]
Hi, 
Thank you for having this project public, especially the code for downloading images. 
I'm working on a similar research topic where I aim to detect rare morphologies using Anomaly detection methods. 
Could you please confirm if the catalog of detected Ring Galaxies in [ringcoords.csv](https://github.com/harishk30/RingGalaxiesCNNAnalysis/blob/main/ringcoords.csv) have in-fact been cross-verified by an expert or some relevant source to confirm their correctness? 
If so I would actually be interested in using it as a dataset for my project as well.

**Comment by harishk30** [comment]
Resolved via email discussion.
